@startuml
actor Guest
actor Patient
actor Doctor
actor Nurse
actor ChiefPhysician

Guest --[#black]> (Регистрация)
Guest -[#black]> (Авторизация в приложение)

Patient ---[#red]> (Посмотреть записи на прием)
Patient --[#red]> (Посмотреть лечения)
Patient --[#red]> (Посмотреть диагнозы)
Patient --[#red]> (Посмотреть профиль)
Patient ---[#red]> (Записаться на прием)

Doctor -[#green]> (Посмотреть список пациентов)
(Посмотреть список пациентов) -[#green]> (Посмотреть информацию о пациенте): extend
(Посмотреть информацию о пациенте) --[#green]> (Посмотреть записи на прием): extend
(Посмотреть информацию о пациенте) --[#green]> (Посмотреть лечения): extend
(Посмотреть информацию о пациенте) --[#green]> (Посмотреть диагнозы): extend
Doctor -[#green]> (Посмотреть профиль)
Doctor --[#green]> (Назначить диагноз пациенту)
Doctor ---[#green]> (Назначить лечение пациенту)
(Назначить лечение пациенту) ---[#green]> (Назначить процедуру): include
(Назначить лечение пациенту) --[#green]> (Назначить лекарства): include
(Назначить лечение пациенту) --[#green]> (Назначить операцию): include
Doctor --[#green]> (Выписать пациента)

Nurse --[#pink]> (Посмотреть профиль)
Nurse --[#pink]> (Назначить процедуру)
Nurse --[#pink]> (Назначить лекарства)

ChiefPhysician -[#blue]> (Зарегистрировать персонал)
(Зарегистрировать персонал) -[#blue]> (Зарегистрировать врача): include
(Зарегистрировать персонал) --[#blue]> (Зарегистрировать медсестру): include
ChiefPhysician -[#blue]> (Выписать пациента)
ChiefPhysician -[#blue]> (Назначить диагноз пациенту)
ChiefPhysician ---[#blue]> (Посмотреть профиль)
ChiefPhysician -[#blue]> (Назначить лечение пациенту)


@enduml